// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpt2OlLiCtGTbRM1WNX7kOemasf9yY0I',
    appId: '1:431054007296:android:683e30099ff624e901fce5',
    messagingSenderId: '431054007296',
    projectId: 'ecommerce-1c7eb',
    storageBucket: 'ecommerce-1c7eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGVQ7R7pCcg-yQS8AI0TvMvduvBtXWqOE',
    appId: '1:431054007296:ios:d6d3b86b35cd354b01fce5',
    messagingSenderId: '431054007296',
    projectId: 'ecommerce-1c7eb',
    storageBucket: 'ecommerce-1c7eb.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGVQ7R7pCcg-yQS8AI0TvMvduvBtXWqOE',
    appId: '1:431054007296:ios:d6d3b86b35cd354b01fce5',
    messagingSenderId: '431054007296',
    projectId: 'ecommerce-1c7eb',
    storageBucket: 'ecommerce-1c7eb.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
